name: Build and Deploy to ACA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"8f2c1ccb-6cd8-49c9-a941-90f46bdf134f","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"5a775aa2-0a21-483c-9818-460896054c2e","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Build and deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          # Docker Hub Credentials
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          
          # Azure Target
          resourceGroup: container-labs-miri-rg
          containerAppName: frontendapp
          
          # Build Configuration
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          # This line is the fix: it forces the use of your username
          imageToDeploy: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontendapp-node:${{ github.sha }}