name: Build and Deploy to ACA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This forces your username into the tag so Docker Hub can't deny it
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontendapp-node:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"8f2c1ccb-6cd8-49c9-a941-90f46bdf134f","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"5a775aa2-0a21-483c-9818-460896054c2e","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az extension add --name containerapp --upgrade
            az containerapp update \
              --name frontendapp \
              --resource-group container-labs-miri-rg \
              --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontendapp-node:latest